#Expyriment 1.0.0 (Python 3.11.2), .xpe-file, coding: UTF-8
#date: Wed Sep 24 2025 12:09:30
#sha1: 35dacc
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='anna', release='6.1.0-37-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.1.140-1 (2025-05-22)', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
560,design,log,
#design: #exp: Two Squares
#design: block_cnt,block_id,trial_cnt,trial_id
560,design,logged,
560,Experiment,started
561,Stimulus,presented,1
582,Stimulus,presented,0
584,stderr,received,'Traceback (most recent call last):'
584,stderr,received,'  File "/home/anna/ENS/3A/cogsup/exp_app/PPE/Week-2/Exercises/two_squares.py", line 38, in <module>'
584,stderr,received,'    line_2.plot(b1)'
584,stderr,received,'                ^^'
584,stderr,received,"NameError: name 'b1' is not defined. Did you mean: 'bl'?"
